### ISSUE TITLE
ws1

### ISSUE THREAD

**Issue by AmanChaturvedi24** [xiakshay/Soft-Computing-Experiments#1]
![WhatsApp Image 2022-11-17 at 10 15 44](https://user-images.githubusercontent.com/73428540/202358411-a838f9f3-fc45-4ffb-95ae-a1004c456aae.jpeg)
![WhatsApp Image 2022-10-04 at 13 57 32](https://user-images.githubusercontent.com/73428540/202358447-2e56fdbf-3b22-4e9e-b3fd-407935b7e505.jpeg)
![WhatsApp Image 2022-10-04 at 13 57 32 (1)](https://user-images.githubusercontent.com/73428540/202358456-ae10070b-1353-4995-8258-a1f88f3de24b.jpeg)

**Comment by xiakshay** [comment]
TY
